### ISSUE TITLE
Use terminal colors?

### ISSUE THREAD

**Issue by dgudim** [deponian/logalize#1]
I am trying to configure logalize to use standard colors from the terminal, but it says: `foreground color green doesn't match ^(#[[:xdigit:]]{6}|[[:digit:]]{1,3})?$ regexp` are standard colors not supported?

**Comment by deponian** [comment]
@dgudim Hi!
Standard colors are supported only by number in the ANSI table, not by name. So it's number `3` for green color, `9` for red and so on. You can find the number you need here: https://www.ditig.com/publications/256-colors-cheat-sheet

**Comment by dgudim** [comment]
Wow, that was fast :) thanks!
