### ISSUE TITLE
paginating output

### ISSUE THREAD

**Issue by muzzol** [deponian/logalize#4]
I'm trying to paginate output to less but I lose colours either with 'less -R' or 'less -r'

is there a way to paginate output without losing colours?

can I suggest integrating pagination into logalize itself?

**Comment by deponian** [comment]
Hi!
The problem lies somewhere in the process of detecting terminal capabilities. Output to `stdout` is different then output to a pipe. So you don't lose colors when reroute output to Less. Logalize just doesn't add them in the first place.
I'll see what I can do.

**Comment by deponian** [comment]
@muzzol It's done! Check version 0.4.2. Now you should be able to see colors in `less`
